### ISSUE TITLE
Crear el modelo entidad relacion del proyecto

### ISSUE THREAD

**Issue by MARIOVALEN** [MARIOVALEN/GRUPO20T7#4]

**Comment by MARIOVALEN** [comment]
Se dejó el MER tal cual se expone en el enunciado del Proyecto Grupo 20 Profe: MARIO ALBERTO SANCHEZ CASTRO para el Ciclo 3. No se enuncia nada de las relaciones entre las clases, herencias y demás, que significarían las flechas y conexiones en el diagrama. Igual se va a trabajar gran parte del código en clase y si después hay que adicionarle algo se hará.

**Comment by efradev** [comment]
[MER  AVIONES Ciclo 3.pdf](https://github.com/MARIOVALEN/GRUPO20T7/files/7218894/MER.AVIONES.Ciclo.3.pdf)

Archivo Agragdo
